include:
  - project: 'personal/infrastructure_lives'
    file: '/pipeline/backend.yml'
    ref: main

variables:
  PROJECT_NAME: "MOINEX"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - test
  - quality
  - build
  - deploy

unit_test:
  stage: test
  image: eclipse-temurin:21-jdk
  script:
    - chmod +x ./gradlew
    - ./gradlew clean build jacocoTestReport
  artifacts:
    paths:
      - build/classes
      - build/libs
      - build/reports/jacoco/test/jacocoTestReport.xml
    when: always
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .gradle/wrapper
      - .gradle/caches
    policy: pull-push
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_MERGE_REQUEST_ID'
      when: always
    - when: never
      allow_failure: false

build_migration:
  rules:
    - when: never

deploy_migration:
  rules:
    - when: never

deploy_migration_rollback:
  rules:
    - when: never

build_app:
  rules:
    - when: never

deploy_app:
  rules:
    - when: never

