/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    kotlin("jvm") version "2.0.0"
    kotlin("plugin.spring") version "2.0.0"
    kotlin("plugin.jpa") version "2.0.0"
    id("org.springframework.boot") version "3.4.5"
    id("io.spring.dependency-management") version "1.1.7"
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("org.beryx.jlink") version "3.0.1"
    id("org.jlleitschuh.gradle.ktlint") version "12.1.0"
    jacoco
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    // Kotlin
    implementation(kotlin("stdlib"))
    implementation(kotlin("reflect"))

    // Spring Boot
    implementation(libs.org.springframework.boot.spring.boot.starter)
    implementation(libs.org.springframework.boot.spring.boot.starter.data.jpa)

    // Database
    implementation(libs.org.xerial.sqlite.jdbc)
    implementation(libs.org.hibernate.orm.hibernate.community.dialects)
    testImplementation(libs.com.h2database.h2)

    // JavaFX
    implementation(libs.org.openjfx.javafx.controls)
    implementation(libs.org.openjfx.javafx.fxml)
    implementation(libs.com.jfoenix.jfoenix)

    // Utilities
    implementation(libs.com.opencsv.opencsv)
    implementation(libs.org.reflections.reflections)
    implementation(libs.net.objecthunter.exp4j)
    implementation(libs.org.json.json)
    implementation(libs.net.minidev.json.smart)

    // Logging
    implementation(libs.org.slf4j.slf4j.api)
    implementation(libs.ch.qos.logback.logback.classic)

    // Flyway
    implementation("org.flywaydb:flyway-core:11.3.4")

    // Code Quality
    implementation(libs.com.google.googlejavaformat.google.java.format)

    // Lombok
    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)

    // Testing
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    testImplementation(kotlin("test"))
}

group = "org.moinex.app"
version = "1.0-SNAPSHOT"
description = "Moinex"

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

javafx {
    version = "23.0.1"
    modules = listOf("javafx.controls", "javafx.fxml")
}

springBoot {
    mainClass.set("org.moinex.app.App")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.release.set(21)
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

tasks.withType<Test> {
    useJUnitPlatform()
}

tasks.named<org.springframework.boot.gradle.tasks.bundling.BootJar>("bootJar") {
    archiveFileName.set("moinex.jar")
    mainClass.set("org.moinex.app.App")
}

jacoco {
    toolVersion = "0.8.13"
}

tasks.jacocoTestReport {
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}

ktlint {
    version.set("1.0.1")
    android.set(false)
    outputToConsole.set(true)
    ignoreFailures.set(false)
    filter {
        exclude("**/generated/**")
        exclude("**/build/**")
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        jvmTarget = "21"
        freeCompilerArgs =
            listOf(
                "-Xjsr305=strict",
                "-Xemit-jvm-type-annotations",
            )
    }
}
