sonar.organization=luk3rr
sonar.projectKey=luk3rr_MOINEX
sonar.sources=src/main/kotlin
sonar.tests=src/test/kotlin

# Kotlin binaries
sonar.java.binaries=build/classes/kotlin/main
sonar.java.test.binaries=build/classes/kotlin/test
sonar.java.libraries=build/libs/*.jar

# Kotlin specific
sonar.kotlin.source.version=2.1

# Python scripts
sonar.python.version=3.9

# Coverage
sonar.coverage.exclusions=**/app/**,**/common/**,**/config/**,**/exception/**,**/model/**,**/repository/**,**/ui/**,
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
