package org.moinex.model.enums

enum class NotificationType {
    BUDGET_GROUP_EXCEEDED,
    RECURRING_TRANSACTION_PROCESSED,
    RECURRING_CREDIT_CARD_DEBT_PROCESSED,
    WALLET_TRANSACTION_CREATED,
    CREDIT_CARD_TRANSACTION_CREATED,
    GOAL_ACHIEVED,
    GENERIC_INFO,
    GENERIC_WARNING,
    GENERIC_ERROR,
}
